
from .base import BaseDataAdapter

class DisclosureAdapter(BaseDataAdapter):
    def source_name(self) -> str:
        return "disclosure"

    def healthcheck(self) -> bool:
        return True

    def get_announcements(self, trade_date: str): ...
    def get_earnings_forecasts(self, start_date: str, end_date: str): ...
    def get_major_orders(self, start_date: str, end_date: str): ...
    def get_shareholder_changes(self, start_date: str, end_date: str): ...
    def get_investor_relations(self, start_date: str, end_date: str): ...
