
from .base import BaseDataAdapter

class IndustryDataAdapter(BaseDataAdapter):
    def source_name(self) -> str:
        return "industry_data"

    def healthcheck(self) -> bool:
        return True

    def get_prices(self, trade_date: str): ...
    def get_inventory(self, trade_date: str): ...
    def get_capacity_utilization(self, trade_date: str): ...
    def get_shipments(self, trade_date: str): ...
    def get_capex(self, trade_date: str): ...
