
from .base import BaseDataAdapter

class MarketDataAdapter(BaseDataAdapter):
    def source_name(self) -> str:
        return "market_data"

    def healthcheck(self) -> bool:
        return True

    def get_trade_calendar(self, start_date: str, end_date: str): ...
    def get_major_indices(self, trade_date: str): ...
    def get_market_breadth(self, trade_date: str): ...
    def get_market_turnover(self, trade_date: str): ...
    def get_limit_stats(self, trade_date: str): ...
    def get_sector_performance(self, trade_date: str): ...
    def get_concept_performance(self, trade_date: str): ...
    def get_stock_daily(self, trade_date: str): ...
    def get_stock_intraday_summary(self, trade_date: str): ...
